spring:
  datasource:
    url: jdbc:postgresql://centerbeam.proxy.rlwy.net:22102/railway?sslmode=require
    username: postgres
    password: LjqSHFQRkoBTIfUKlYXnUFsuHiPiyWyU
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false