spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ExpenseTrackerDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: matar

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

