server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://gondola.proxy.rlwy.net:23750/railway?sslmode=require
    username: postgres
    password: enyqbzuBAclMLabLUVwWWOBwOBxQocAy
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false